ERROR    fs_past_stat_parser.py[LINE:93 2020-08-01 17:11][ForkPoolWorker-6][get_more_events] Button show more events not found url {url}
Traceback (most recent call last):
  File "/home/max/Projects/football-stat-scraper/stat_scraper/fs_past_stat_parser.py", line 91, in get_more_events
    more_event_btn.click()
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: headless chrome=84.0.4147.89)

ERROR    fs_past_stat_parser.py[LINE:93 2020-08-01 17:11][ForkPoolWorker-9][get_more_events] Button show more events not found url {url}
Traceback (most recent call last):
  File "/home/max/Projects/football-stat-scraper/stat_scraper/fs_past_stat_parser.py", line 91, in get_more_events
    more_event_btn.click()
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: headless chrome=84.0.4147.89)

ERROR    fs_live_stat_parser.py[LINE:16 2020-08-01 17:17][ForkPoolWorker-17][get_html] Error receive html https://www.flashscore.com/match/AeNejKpo
Traceback (most recent call last):
  File "/home/max/Projects/football-stat-scraper/stat_scraper/fs_live_stat_parser.py", line 9, in get_html
    driver = get_driver()
  File "/home/max/Projects/football-stat-scraper/stat_scraper/init_driver.py", line 10, in get_driver
    driver = webdriver.Chrome(options=chrome_options,
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (chrome not reachable)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

ERROR    speed_run_test.py[LINE:30 2020-08-01 17:17][ForkPoolWorker-17][run_parse] ERROR RUN PARSE ON URL https://www.flashscore.com/match/AeNejKpo
Traceback (most recent call last):
  File "/home/max/Projects/football-stat-scraper/tests/speed_run_test.py", line 27, in run_parse
    summary_stat.update(get_live_stat(url))
  File "/home/max/Projects/football-stat-scraper/stat_scraper/fs_live_stat_parser.py", line 96, in get_live_stat
    live_stat.update(get_main_stat(url))
  File "/home/max/Projects/football-stat-scraper/stat_scraper/fs_live_stat_parser.py", line 67, in get_main_stat
    html = get_html(url)
  File "/home/max/Projects/football-stat-scraper/stat_scraper/fs_live_stat_parser.py", line 17, in get_html
    return html
UnboundLocalError: local variable 'html' referenced before assignment
ERROR    fs_past_stat_parser.py[LINE:93 2020-08-01 17:18][ForkPoolWorker-20][get_more_events] Button show more events not found url {url}
Traceback (most recent call last):
  File "/home/max/Projects/football-stat-scraper/stat_scraper/fs_past_stat_parser.py", line 91, in get_more_events
    more_event_btn.click()
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: headless chrome=84.0.4147.89)

ERROR    fs_past_stat_parser.py[LINE:93 2020-08-01 17:18][ForkPoolWorker-16][get_more_events] Button show more events not found url {url}
Traceback (most recent call last):
  File "/home/max/Projects/football-stat-scraper/stat_scraper/fs_past_stat_parser.py", line 91, in get_more_events
    more_event_btn.click()
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: headless chrome=84.0.4147.89)

ERROR    fs_past_stat_parser.py[LINE:92 2020-08-02 13:50][ForkPoolWorker-6][get_more_events] Button show more events not found url {url}
Traceback (most recent call last):
  File "/home/max/Projects/football-stat-scraper/stat_scraper/fs_past_stat_parser.py", line 90, in get_more_events
    more_event_btn.click()
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: headless chrome=84.0.4147.89)

ERROR    fs_past_stat_parser.py[LINE:92 2020-08-02 13:50][ForkPoolWorker-4][get_more_events] Button show more events not found url {url}
Traceback (most recent call last):
  File "/home/max/Projects/football-stat-scraper/stat_scraper/fs_past_stat_parser.py", line 90, in get_more_events
    more_event_btn.click()
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: headless chrome=84.0.4147.89)

ERROR    fs_past_stat_parser.py[LINE:92 2020-08-02 13:55][ForkPoolWorker-20][get_more_events] Button show more events not found url {url}
Traceback (most recent call last):
  File "/home/max/Projects/football-stat-scraper/stat_scraper/fs_past_stat_parser.py", line 90, in get_more_events
    more_event_btn.click()
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: headless chrome=84.0.4147.89)

ERROR    fs_past_stat_parser.py[LINE:92 2020-08-02 13:55][ForkPoolWorker-15][get_more_events] Button show more events not found url {url}
Traceback (most recent call last):
  File "/home/max/Projects/football-stat-scraper/stat_scraper/fs_past_stat_parser.py", line 90, in get_more_events
    more_event_btn.click()
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/max/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: headless chrome=84.0.4147.89)

